config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: "sessions"}

  devise_scope :user do
    authenticated :user do
      get "/users/sign_out" => "devise/sessions#destroy", :as => :service_sign_out
      resources :users
      resources :groups do
        member do
          post   :add,    to: 'groups#add_user'
          delete :remove, to: 'groups#remove_user'
        end
      end
      resource :profile, except: [:index,:destroy,:create]
      root to: "profiles#show", as: :authenticated_root
    end



    unauthenticated :user do
      root to: "sessions#new", as: :unauthenticated_root

      get "/setup" => "setup#index"
      post "/setup/create" => "setup#create"
    end
  end

end

app/models/group.rb
class Group
  include Mongoid::Document
  include Mongoid::Timestamps
  include Bagable

  field :name
  field :query

  has_and_belongs_to_many :users
  validates_presence_of :name

  def data
    {
      name => query
    }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy, :add_user, :remove_user]
  before_action :set_user,  only: [:add_user, :remove_user]

  def index
    @groups = Group.all
  end

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def remove_user
    @user.groups.delete(@group)
    @user.save
    respond_to do |format|
      format.html { redirect_to @group, notice: 'User was successfully removed.' }
    end
  end

  def add_user
    @user.groups.push(@group)
    @user.save
    respond_to do |format|
      format.html{redirect_to @group, notice: 'User was Added Successfully'}
    end
  end

  private
  def set_group
    @group = Group.find(params[:id])
  end

  def set_user
    @user = User.find(params[:user_id])
  end

  def group_params
    params[:group].permit(:name,:query)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.slim
.container-fluid
  = form_for @group, html: {class: 'form-horizontal' } do |f|
    - if @group.errors.any?
      #error_explanation
        h2 = "#{pluralize(@group.errors.count, "error")} prohibited this group from being saved:"
        ul
          - @group.errors.full_messages.each do |message|
            li = message
    .form-group
      .col-md-12
        = f.label 'Group Name', class: "control-label"
        = f.text_field :name, autofocus: true, class: "form-control", placeholder: "Name"
    .form-group
      .col-md-12
        = f.label 'Chef Query', class: "control-label"
        = f.text_field :query, autofocus: true, class: "form-control", placeholder: "ex. chef_environment:staging"
    .form-group
      .col-md-12
        = f.submit 'Save',class: "btn btn-lg btn-primary btn-block"

app/views/groups/edit.html.slim
.container-fluid.form-layout
  .panel.panel-default
    .panel-heading
      h2 Editing Group
    .panel-body
      == render 'form'
    .panel-footer
      = link_to 'Show', @group
      '|
      = link_to 'Back', groups_path

app/views/groups/index.html.slim
h1 Listing groups

table.table.table-hover.table-condensed.data-table
  thead
    tr
      th Name
      th Query
      th

  tbody
    - @groups.each do |group|
      tr
        td = group.name
        td = group.query
        td = link_to 'Show', group
        td = link_to 'Edit', edit_group_path(group)
        td = link_to 'Destroy', group, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Group', new_group_path

app/views/groups/new.html.slim
.container-fluid.form-layout
  .panel.panel-default
    .panel-heading
      h2 New Group
    .panel-body
      == render 'form'
    .panel-footer
      = link_to 'Back', groups_path

app/views/groups/show.html.slim
.container-fluid
  .panel.panel-default
    h2 Members of Group: #{@group.name}
  .panel.body
    table.table.table-condensed.table-bordered.table-hover
      tbody
        - @group.users.each do |user|
          tr
            td = link_to user.email, profile_path(user)
            td = link_to 'Remove', remove_group_path(user_id: user.id), data: {confirm: 'Are you sure?'}, method: :delete
  .user-form-links
    =link_to 'Back' , groups_path