config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {sessions: "sessions"}

  devise_scope :user do
    authenticated :user do
      get "/users/sign_out" => "devise/sessions#destroy", :as => :service_sign_out
      resources :users
      resources :groups do
        member do
          post   :add,    to: 'groups#add_user'
          delete :remove, to: 'groups#remove_user'
        end
      end
      resource :profile, except: [:index,:destroy,:create]
      root to: "profiles#show", as: :authenticated_root
    end



    unauthenticated :user do
      root to: "sessions#new", as: :unauthenticated_root

      get "/setup" => "setup#index"
      post "/setup/create" => "setup#create"
    end
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Bagable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :registerable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  field :ssh_key
  field :admin, type: Boolean, default: false
  field :name, type: String
  field :login_name, type: String
  field :user_id, type: Integer

  has_and_belongs_to_many :groups

  validates_presence_of :login_name, :user_id
  validates_uniqueness_of :login_name, :user_id

  def force_profile_update?
    newcomer? and ssh_key.nil?
  end

  def newcomer?
    sign_in_count <= 1
  end

  def to_key
    if key = super
      key = key.map(&:to_s)
    end
    key
  end

  def data
    {
      login_name => {
        'name'    => name,
        'user_id' => user_id,
        'ssh_key' => ssh_key,
        'groups'  => groups.collect(&:name)
      }
    }
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def index

  end

  def ldap_settings

  end
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/ldap_settings.html.slim
.container-fluid
  = form_for @user, html: {class: 'form-horizontal'}, :url => setup_create_path(@user) do |f|
    - if @user.errors.any?
      #error_explanation
        h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
        ul
          - @user.errors.full_messages.each do |message|
            li = message
    .form-group
      .col-md-4
      .col-md-4
        = f.collection_check_boxes :group_ids, Group.all, :to_param, :name, checked: @user.groups.map(&:id) do |b|
          = b.label(:"data-value" => b.value, class: "checkbox-inline control-label" ) { b.check_box + ' ' + b.text }
    .form-group
      .col-md-4
      .col-md-4
        = f.label 'Login Id', class: "control-label"
        = f.text_field :login_name, class: "form-control", placeholder: "Name"
    .form-group
      .col-md-4
      .col-md-4
        = f.label 'Full Name', class: "control-label"
        = f.text_field :name, class: "form-control", placeholder: "Name"
    .form-group
      .col-md-4
      .col-md-4
        = f.label 'Email address', class: "control-label"
        = f.email_field :email, class: "form-control", placeholder: "Email address"
    .form-group
      .col-md-4
      .col-md-4
        input type="text" name="domain" id="domain" placeholder="Organisation Domain" class="form-control"
    - if @user.encrypted_password.blank?
      .form-group
        .col-md-4
        .col-md-4
          = f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Set Password"
      .form-group
        .col-md-4
        .col-md-4
          = f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Confirm new Password"
    .form-group
      .col-md-4
      .col-md-4
        = f.submit 'Save',class: "btn btn-lg btn-primary btn-block"